### PR TITLE
Embeding working with performance == 1 or 2

### PR DESCRIPTION
**Pull request by jeammimi**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Nice that it's working, could you make sure that the previous value is set by putting it in a try/finally block:
```python
try:
  ....
finally:
  pass # this code will execute whatever happens
```

**Comment by maartenbreddels** [comment]
👍

**Comment by maartenbreddels** [comment]
merge, thanks again!

**Comment by jeammimi** [comment]
You are wellcome! Now you can set performance == 1 by default :)

**Comment by maartenbreddels** [comment]
I think that is true actually!
Also, the performance = 2 case will be supported for the next release of ipywidgets, https://github.com/ipython/ipywidgets/pull/1194 got merged. So then we can have sequences with non-constant length arrays. Not sure what we need to do with performance == 2, then, maybe just remove the performance stuff, and by default try to send it as binary.

**Pull request merged**
