### PR TITLE
Unit testing for TypeScript/JavaScript code

### PR DESCRIPTION
**Pull request by OlehKSS**
Tests are supposed to written in TypeScript, so  webpack was configured to work with TypeScript as well.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Just letting you know I'm on vacation. Will take a look as soon as I can!

**Comment by OlehKSS** [comment]
Sorry for disturbing you:)

**Comment by maartenbreddels** [comment]
Sorry for not getting back to you sooner! Doing my best, but it is a busy
period

(from mobile phone)

**Comment by maartenbreddels** [comment]
Great work, we should be adding some unittests, especially the transitions are complex, wouldn't hurt to have tests for those so refactoring will be easier

**Pull request merged**
