### PR TITLE
moebius_example.html

### PR DESCRIPTION
**Pull request by rpanai**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thanks!
I've added a few fixed, feel free to add some description/credits in the first markdown cell!

**Comment by rpanai** [comment]
> Thanks!
> I've added a few fixed, feel free to add some description/credits in the first markdown cell!

Do I need to make a new PR for this?

**Comment by maartenbreddels** [comment]
No, you can pull in my changes (git pull or git pull --rebase if you made local changes), commit your changes, and push again on this branch/PR.
It would be nice if you credit yourself, and maybe @deeplook.

**Comment by rpanai** [comment]
@maartenbreddels done!

**Comment by maartenbreddels** [comment]
Excellent, thanks for you first contribution to ipyvolume!

**Pull request merged**
