### PR TITLE
adding docstring for animation

### PR DESCRIPTION
**Pull request by choldgraf**
adds an extra sentence to a few of your docstrings...lemme know if you'd like a different wording or something

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thanks for attacking this.
My 'plan' was to add the snippet `(can be a sequence)`, and somewhere on the top explain that this can be an animation, but that is too abstract and requires you to read more than just that docstring, which is bad. What about:
```
numpy array of shape (N,) or (S, N) with x positions, when of shape (S, N), the first dimension will be used for frames in an animation.
```
And similar for the rest?

**Comment by choldgraf** [comment]
sounds fine to me - that's pretty close to the wording I've got here as well. I'll use your wording, though will use a period in between the first part of the docstring and this part so that it's a little more modular...cool?

**Comment by maartenbreddels** [comment]
yeah, basically remove the 'can be a sequence', and then I'll trust you on the proper language 👍

**Comment by choldgraf** [comment]
ok so how is this?

**Comment by maartenbreddels** [comment]
Excellent, thanks 👍

**Comment by choldgraf** [comment]
woo!

**Pull request merged**
