### PR TITLE
Add TransferFunction editing notebook

### PR DESCRIPTION
**Pull request by OliverEvans96**
Create a widget interface with bqplot's HandDraw to interactively edit TransferFunctions, as discussed in #74 .

image

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I tried it out, and it's really nice! I like the idea of using bqplot. Do you have any more plans with this?

**Comment by OliverEvans96** [comment]
That was the extent of my plans so far for this widget. I thought it would
be helpful in order to visualize and edit transfer functions.

Ultimately, it would be nice to have a few classes of transfer functions
ready to use for ipyvolume that could be easily chosen with a kwarg to
volshow, perhaps.

Do you have any thoughts or suggestions? About the theory of transfer
functions or about how to use this type of interactive widget?

Oliver

**Comment by maartenbreddels** [comment]
What I'd like to see, is an instant change of the transfer function, I think that requires a change in bqplot's handdrawn widget. I'm thinking of making this into an example to put on the documentation page, or something like a 'contribute' subpackage where this could go so other people might use it. But given the discussion in #74 it might be too early :)

**Comment by OliverEvans96** [comment]
What do you mean by that? As in you change the sliders in quickvolshow and
the rgba curves update automatically? If so, I thought about this. I put
the Reload TF button to do this manually, but if I were to have this happen
automatically, I think it would cause infinite recursion: changing the
curves changes the TF which changes the curves, etc.

If the two were linked with traitlets.link, this wouldn't be an issue, but
I'm currently using observe to set the TF since I'm combining data from 4
curves into one numpy rgba array. If you have any thoughts about this, let
me know!

If you meant something else by an instant change in the TF, then I'm not
sure I understood.

I'd be glad to change things around if you'd like so that it would make for
a good example.

**Comment by maartenbreddels** [comment]
When you draw by hand, it only updates when you let the mouse button go (at least here), would be nice if every mouse change it would update the rgba values.

There is also traitlets.dlink/ipywidgets.dlink (which does a directional like, and ipwidgets' one sets it on the js side).

**Comment by OliverEvans96** [comment]
Ah, yes - I see what you mean. I agree, that might require modifying
bqplot. But it seems reasonable that there should be some analogue of
continupus_update for handdraw. I'm thinking this should be doable.

**Comment by OliverEvans96** [comment]
I had a thought for the widget: it would be great to specify other color
spaces. In particular, specifying hsl/alpha would be neat.

I found  another idea I thought made a lot of sense in this tutorial:
http://graphicsrunner.blogspot.com/2009/01/volume-rendering-102-transfer-functions.html?m=1

In their TF editing widget, you specify the endpoints of a horizontal
linear colorbar, and then have a single alpha curve to edit as a function
of data value.
When I've explained the current system with the 3 RGB gaussians to my
professors, it's always taken a minute for them to understand that red is
low, green is medium, and blue is high. I think having a single linear
color gradient from low to high could eliminate that confusion.

**Comment by maartenbreddels** [comment]
This is exactly the rendering I want to be able to reproduce! I lost the link, so thanks for putting it here. This person also has some interesting ideas for optimization, really worth a look.

I actually had an implementation with a color gradient (all the colormaps from matplotlib) and it is not really great. If your 'alpha bumps' are near eachother, the will also have a quite similar color, and are impossible to distinguish. The red, green, blue sequence for me is easy to remember :)

**Pull request closed without merging**
