### PR TITLE
drop 2.7, add 3.8

### PR DESCRIPTION
**Pull request by glyg**
I'm using 3.8 already, IDK if you want to put it in the matrix

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Yes, good idea!

**Comment by glyg** [comment]
btw I use pytest with nbval to run notebooks as tests (to replace runipy if needed)

**Comment by glyg** [comment]
Ok it passed (except for a small lowering of the coverage).

Should stating that python 2.7 is not supported be made clear elsewhere?

**Comment by maartenbreddels** [comment]
I'll do the changelog afterwards, so I'll see this in the gitlog!

I'm working on setting up testing with screenshots, that should replace the notebook testing.

**Comment by maartenbreddels** [comment]
Thanks!

**Pull request merged**
