### PR TITLE
Added support for ipv.figure(ipv.Figure) syntax

### PR DESCRIPTION
**Pull request by TimoFriedri**
In reference to this issue: #105 

Downside of all the Figure handling atm is that one has to take care not to accidentally use ipv.Figure instead of ipv.figure in your experiments.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Looking good, thanks!
Would you mind adding a unittest, ala:
https://github.com/QuantStack/ipysheet/blob/master/ipysheet/test_all.py#L10
you can add it to:
https://github.com/maartenbreddels/ipyvolume/blob/master/ipyvolume/test_all.py
and install/run `py.test`

**Comment by TimoFriedri** [comment]
Hi,

I will do it soon. I have some issues with py.test. Complaining about missing traittypes which is definitely installed in mit env.

I have to fix that first

**Comment by TimoFriedri** [comment]
Hi, I need support.

I have install ipyvolume for the fork in an Conda Env via pip install -e.
In this env I have also the package traittypes.
If I import traittypes now, the traittypes.py file in ipyvolume is used instead of the package traittypes, which break a lot, including running the py.test

In my env where I have install ipyvolume from conda-forge, everything works as expected.

Any idea?
Thanks

**Comment by TimoFriedri** [comment]
I have tried to fix my traittypes import issue but haven't succeeded yet.

I run 
 `py.test ./ipyvolume/test_all.py`

Then I get that Error:

``` 
py.test ./ipyvolume/test_all.py 
===================================== test session starts ======================================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: .../github/ipyvolume, inifile:
collected 0 items / 1 errors 

============================================ ERRORS ============================================
____________________________ ERROR collecting ipyvolume/test_all.py ____________________________
ImportError while importing test module '.../github/ipyvolume/ipyvolume/test_all.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ipyvolume/__init__.py:5: in <module>
    from .widgets import *
ipyvolume/widgets.py:4: in <module>
    from traittypes import Array
E   ModuleNotFoundError: No module named 'traittypes'
!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================== 1 error in 0.52 seconds ==================================== 
```

For some reason it is using the traittypes.py in ipyvolume. If I open ipython and import traittypes, I can check with `traittypes.__file__` that the correct package is used.

**Comment by maartenbreddels** [comment]
This only happens with py.test?
can you give me the output of:
$ `which python`
and
$ `which py.test`

**Comment by TimoFriedri** [comment]
Thanks, you gave me the correct idea for what might be wrong. pytest was still not installed in my env, only in root. This caused the issue. I have somehow overseen this the whole time.

I'll update the PR soon.

**Comment by maartenbreddels** [comment]
Excellent, thanks!

**Pull request merged**
