### PR TITLE
Modified for the embeding to work in case of performance equal one

### PR DESCRIPTION
**Pull request by jeammimi**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I wonder, can't we do sth like this in embed_html?:
```python
previous = ipyvolume.serialiize.performance
try:
   ipyvolume.serialiize.performance = 0
  ...
         for widget in widgets:
             if not all:
                 get_state(widget, state, drop_defaults=drop_defaults)
  ...
finally:
  ipyvolume.serialize.performance = previous

**Comment by jeammimi** [comment]
I am not sure how it works, but this get_state get the value from the js no?

**Comment by maartenbreddels** [comment]
No, it will basically call the to_json, which will give a list for performance=0, can you try that out?

**Comment by jeammimi** [comment]
Are you sure, because it keep the state of the widget as it is shown.

**Comment by maartenbreddels** [comment]
True, but the python side is always synced. And it will always go though a from_json path etc.

**Comment by jeammimi** [comment]
ok, I ll try

**Comment by jeammimi** [comment]
ok it works, I will create another pull request

**Pull request closed without merging**
